---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.17.4
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: detect-private-key

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.19.0
    hooks:
      - id: toml-sort
        args: [--in-place]

  - repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
      - id: docformatter

  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
      - id: markdownlint
        args: [--style, cirosantilli, --rules, '~first-header-h1,~first-line-h1,~no-trailing-punctuation']

  - repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
      - id: isort
        additional_dependencies: [toml]

  - repo: https://github.com/psf/black
    rev: 21.4b2
    hooks:
      - id: black

#  - repo: https://github.com/life4/flakehell
#    rev: ''
#    hooks:
#      - id: flakehell
#        types: [file, text]
#        files: \.(ipynb|md|py|rst|yaml|yml)$
#        additional_dependencies: [flake8-alfred, flake8-bandit, flake8-black, flake8-bugbear,
#          flake8-builtins, flake8-comprehensions, flake8-docstrings, flake8-logging-format,
#          flake8-markdown, flake8-pytest-style, flake8-typing-imports, flake8-use-fstring,
#          flakehell, darglint, dlint, pep8-naming]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.1.0
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2', --colons, --width, '88']
